name: pokemon_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  flutter_switch: ^0.3.2 #theme değiştirmek için kullanıldı
  shared_preferences: ^2.0.7
  flutter_bloc: ^7.3.1
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.9.2 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"  

flutter:
  uses-material-design: true
  assets:
    - assets/images/no-results.png
